# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Mapper Test

on:
    push:
        branches: [task5-workflow]
    pull_request:
        branches: [task5-workflow]

jobs:
    run_mapper:
        runs-on: ubuntu-latest
        name: Run Tests
        steps:
            - uses: actions/checkout@v2
              name: Checkout out mapper repository
            - uses: actions/checkout@v2
              name: Checkout test repository
              with:
                  path: tests
                  repository: "ccb-hms/ontology-mapper-tests"
                  token: ${{ secrets.MAPPER_TESTING }}
                  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 pytest
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Run mapper on UK Biobank source terms
              run: |
                  python3 t2t.py -s $source_path -t $target_path -min 0 -o "tests/mapper-outputs/ukb-efo/${GITHUB_SHA}.csv"
              env:
                  source_path: ./tests/data/ukb-efo/terms.txt
                  target_path: https://github.com/EBISPOT/efo/releases/download/current/efo.owl
            - name: Setup summary spreadsheet row
              run: |
                  echo -n "${GITHUB_REF},${GITHUB_SHA},ukb-efo/${GITHUB_SHA}.csv," >> $summary_path
              working-directory: tests
              env:
                  summary_path: summary.csv
            - name: Run coverage_error script
              run: |
                  python3 t2t.py $script_path
              env:
                  script_path: ./tests/compare-scripts/coverage_error.py
            - name: Commit changes to tests repo
              run: |
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add mapper-outputs/*
                  git add summary.csv
                  git commit -m "Add files"
              working-directory: tests
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  repository: "ccb-hms/ontology-mapper-tests"
                  github_token: ${{ secrets.MAPPER_TESTING }}
                  directory: "tests"
